#
# Automatically tag a merge with main.
#

name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  release:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0" # make sure we get all commits!

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.52.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: release
          WITH_V: true
